### PR TITLE
Upgrade aws-sdk-go v1.44.37

### PR DESCRIPTION
**Pull request by ripa1993**
Updrading aws-sdk-go to latest version available at moment of writing.

This solves https://github.com/kahing/goofys/issues/671 for me

### CODE REVIEW

**Review by dannycjones — APPROVED** [review]
lgtm, +1

I have built and run the tests for this PR on an EC2 instance against an eu-west-1 Amazon S3 bucket. [test-output](https://github.com/kahing/goofys/files/8950252/tests.log)

**Review by dannycjones — APPROVED** [review]

**Comment by monthonk** [comment]
+1, this looks like a good change. Can we get it merged @kahing ?

**Review by monthonk — APPROVED** [review]

**Comment by ripa1993** [comment]
any chance this will be merged?

**Comment by kahing** [comment]
merged fa288b6265c5da9d5ea2e3edb6ca4ae19d56b437

**Pull request closed without merging**
