### PR TITLE
Switch to using go modules for building.

### PR DESCRIPTION
**Pull request by georgyo**
Using git submodules requires having environment variables being setup locally. The following patch set allows you to just run ```go build``` and have go do the right thing.

There is also fix as go.uuid.NewV4 does not return an error any more.

### CODE REVIEW

**Comment by kahing** [comment]
This is great! Looks like CI currently fails though: https://travis-ci.org/kahing/goofys/jobs/584784568

ref https://github.com/kahing/goofys/issues/371

**Comment by georgyo** [comment]
So, I don't understand what is going on with the Azure Datalake tests.  I even downgraded all the azure modules to the exact version you had before.

The error is as follow, but the test does seem like it should be getting that cleanly from the secure environment variables. Though I don't know enough about both travis-ci and azure to debug this deeper.
```
START: goofys_test.go:2791: GoofysTest.TestAzureDirBlob
START: goofys_test.go:317: GoofysTest.SetUpTest
goofys_test.go:443:
    t.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"failed to get SPT from client credentials: parameter 'clientID' cannot be empty"} ("failed to get SPT from client credentials: parameter 'clientID' cannot be empty")
```

**Comment by georgyo** [comment]
It seems those tests are actually broken, looking at other merge requests which don't even go close to those azure code paths. Cleaned up the commit history so this can be merged.

**Comment by kahing** [comment]
Oh right, the secure variables are only available to master branch (otherwise anyone can create a PR to dump out my credentials). I will look into testing this soonish

**Comment by georgyo** [comment]
@kahing Just seeing if this is still something you would be interested in merging.

**Comment by NefixEstrada** [comment]
What's the status of this? The whole project is impossible to use if this doesn't get merged

**Comment by svaroqui** [comment]
Hi any progress on that merge ? I'm intrested in it because not building when including
import (
	goofys "github.com/kahing/goofys/api"
	common "github.com/kahing/goofys/api/common"

	"fmt"
	"context"
)

**Comment by svaroqui** [comment]
What's the status of this? The whole project is impossible to use if this doesn't get merged

**Comment by georgyo** [comment]
I would need to refresh this for it to be usable again, but I don't think @kahing has much interest in merging this type of change.

**Comment by svaroqui** [comment]
Ok did this 
replace github.com/kahing/goofys => github.com/georgyo/goofys v0.21.0

but it did not make it 
# github.com/kahing/goofys/internal
../../../../pkg/mod/github.com/georgyo/goofys@v0.21.0/internal/backend_adlv1.go:112:9: assignment mismatch: 2 variables but "github.com/satori/go.uuid".NewV4 returns 1 values
../../../../pkg/mod/github.com/georgyo/goofys@v0.21.0/internal/backend_adlv1.go:527:15: assignment mismatch: 2 variables but "github.com/satori/go.uuid".NewV4 returns 1 values

**Comment by kahing** [comment]
e3748e3cdfe2d2f5ca775e6370020ff863ad6599

**Pull request closed without merging**
