### PR TITLE
Add --use-vhost option to enable S3 virtual-hosted–style

### PR DESCRIPTION
**Pull request by t2y**
I want to use virtual hosted style since a proxy server only support virtual hosted style in my environment.

refer to https://github.com/kahing/goofys/pull/351#issuecomment-418610769

Originally, this patch came from @zhenlingcn (#351), so I hope he/she will update the patch and it will be merged. if so, this PR would be closed.

### CODE REVIEW

**Comment by t2y** [comment]
It seems related to https://github.com/kahing/goofys/issues/336#issuecomment-403372784 .

**Comment by t2y** [comment]
I found that goofys does not use aws-sdk-go for first HEAD request to the bucket. URL data should be modified.

```
2019/03/11 18:32:26.046746 s3.DEBUG Use vhost style: https://mybucket.s3-ap-northeast-1.amazonaws.com
2019/03/11 18:32:26.335175 s3.DEBUG HEAD https://mybucket.s3-ap-northeast-1.amazonaws.com = 403 [ap-northeast-1]
```

**Comment by t2y** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

In my environment, the test has passed. Though go version is 1.11.x.

```
$ make
...
OK: 76 passed, 1 skipped
--- PASS: Test (136.33s)
PASS
ok  	github.com/kahing/goofys/internal	136.358s
```

**Comment by t2y** [comment]
I updated travis settings at #404. I want to confirm the tests results after golang version would be updated.

**Comment by t2y** [comment]
@kahing or @gaul Could you review this PR? I think there is no side effect for default behavior.

**Comment by t2y** [comment]
After #404 merged, travis job was succeeded.

```
--- PASS: Test (119.37s)
PASS
ok  	github.com/kahing/goofys/internal	119.400s
```

**Comment by t2y** [comment]
FYI
> Announcement: Amazon S3 will no longer support path-style API requests starting September 30th, 2020

https://forums.aws.amazon.com/ann.jspa?annID=6776

**Comment by kahing** [comment]
Note to self: I merged #351 and released 0.20.0 and forgot that I wanted to revisit this. I want to change the option from #351 to `--use-vhost` like this PR, and also (at some point) do auto-detect and use vhost as the default.

**Comment by t2y** [comment]
Got it. This PR is no longer needed since #351 has merged.

**Pull request closed without merging**
