### PR TITLE
Set mime type of uploaded files. 

### PR DESCRIPTION
**Pull request by reo7sp**

### CODE REVIEW

**Comment by reo7sp** [comment]
Fixes https://github.com/kahing/goofys/issues/54

**Comment by reo7sp** [comment]
Compiled binary: https://github.com/reo7sp/goofys/releases/download/v0.0.5.1/goofys

**Comment by kahing** [comment]
I think rename also needs to be handled?

**Comment by asianchica22** [comment]
So what's the status of this now?

**Comment by AndydeCleyre** [comment]
@reo7sp Can you please add a little explanation so @kahing can merge this?

**Pull request closed without merging**
