### PR TITLE
add credentials in flags

### PR DESCRIPTION
**Pull request by flrossetto**

### CODE REVIEW

**Comment by gaul** [comment]
This is insecure since the credentials flags show up in process listing.  Why doesn't the `${HOME}/.aws/credentials` file suffice?  And if it does not, would environment variable address your use case better?

**Comment by flrossetto** [comment]
`$ {HOME} /. Aws / credentials` is not sufficient and env does not work.

**Comment by nigels-com** [comment]
The env variables seem to be working for me.

I agree with not using credentials on the CLI in production, but not so opposed to supporting it along with a suitably stern warning message.

**Comment by flrossetto** [comment]
modified to get env value.

**Comment by kahing** [comment]
I don't understand this change, what problems are you trying to solve?

**Pull request closed without merging**
